apiVersion: v2
name: codemie-mcp-connect-service
description: A Helm chart for AI/Run MCP Connect service
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://codemie.lab.epam.com
sources:
  - https://gitbud.epam.com/epm-cdme/codemie-mcp-connect-service.git
maintainers:
  - name: AI/Run
    email: SpecialEPM-CDMEDevelopmentTeam@epam.com
